### ISSUE TITLE
维度不同

### ISSUE THREAD

**Issue by sundayzl66** [ChengjiaHanSEU/CrackDiffusion#1]
作者您好，能提供一下您的数据集吗，我用我的数据集跑的时候会显示模型期望的输入和实际提供的输入在维度上不一致，根据您的论文，我把数据集已经都改成了（128,256,3），还是出错，也不知道是什么原因。

**Comment by ChengjiaHanSEU** [comment]
你好，我无法提供您我的数据集，它并不是开源的，此外，请您注意我添加了两份代码，第一份不是论文的内容，它是我的一个额外的尝试但是效果也很不错，代码中对图像的尺寸要求是不同的，建议你使用core part部分的代码。还请注意的是，我的原始数据集不是（128,256,3），所以代码中自带了降采样部分，如果你忽视了这一部分，那么可能会导致维度不统一。

**Comment by sundayzl66** [comment]
好的 谢谢 我再试试  ❀❀❀
